name: deploy to ec2
run-name: haalnam-pushserver 🚀
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, haalnam-push]
    steps:
      - uses: actions/checkout@v4

      - name: env setting
        run: |
          echo "${{ secrets.ENV }}" >> .env

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - run: npm run build
      - name: Check and delete haalnam-push-server if it exists
        run: |
          if pm2 list | grep -q "haalnam-push-server"; then
            echo "Deleting haalnam-push-server..."
            pm2 delete haalnam-push-server
          else
            echo "haalnam-push-server is not running."

      - run: pm2 start npm --name haalnam-push-server -- run start
      # - run: npm run start
